Autogenerate xml
machine-solution/motion_planning_for_manipulators pull request #22
Opened 2023-07-01 20:00 UTC by ThirdAmethystEye

2023-07-05 17:18 UTC, machine-solution requested changes

2023-07-05 17:18 UTC, machine-solution commented on tools/2-dof/manipulator.xml
> +</mujoco>
Перевод строки в конце для красоты.

2023-07-05 17:18 UTC, machine-solution commented on tools/collision_section.txt
Эта часть должна генериться из количества препятствий и звеньев. Возьми код из существующего скрипта как функцию

2023-07-05 17:18 UTC, machine-solution commented on tools/footer.txt
Пометь такие файлы, которые всегда одинаковые как .const.txt

2023-07-05 17:18 UTC, machine-solution commented on tools/merge_in_xml.py
> +    f.write(open('tools/obstacles.txt', 'r').read())
Названия этих двух файлов должны выноситься в переменные как параметры, они будут постоянно меняться

2023-07-05 17:18 UTC, machine-solution commented on tools/merge_in_xml.py
> +with open(f"tools/{dof}-dof/manipulator.xml", "w+") as f:
Тут тоже название как-нибудь склеить из входных данных, чтобы не гигантское и уникальное.

2023-07-05 19:27 UTC, machine-solution commented
А вообще про неизменяемые файлы лучше положить их в папку const, а не формат файла менять

2023-07-07 09:05 UTC, ThirdAmethystEye commented on tools/2-dof/manipulator.xml
> +</mujoco>
Есть такая проблема: если открыть на гитхабе вид файла, то файл отображается без пустой последней строки, в то же время, в редакторе файл отображается с последней пустой строкой. Похоже, что гитхаб съедает последнюю строчку. Это не особая проблема, но тогда нужно открывать файл, если есть сомнения по поводу того, есть ли в нём последняя строчка.(Я прикреплю фотки ниже, чтобы подробнее показать, что происходит)(в этом файле её и правда не было, но в других может быть по-другому)

2023-07-08 07:56 UTC, machine-solution requested changes

2023-07-08 07:56 UTC, machine-solution commented on tools/xml_autogen.py
> +    f.write('    </contact>\n')
Выдели в функцию, может. Чтобы код поприятнее был.

2023-07-08 07:56 UTC, machine-solution commented on tools/xml_autogen.py
> +    f.write('    </contact>\n')
Функция, принимающая в параметры joints и obstacles, если что.

2023-07-08 07:56 UTC, machine-solution commented on tools/const/header.txt
А у тебя же есть .gitignore? .txt файлы аргументов, так называемые артефакты не должны попадать в репозиторий. Эти уже добавленные txt можно удалить командой git rm (-f), больше они (с правильным gitignore) в репозиторий не попадут.
Добавь ещё в .gitignore строчку 
```
/tools/*.xml
```
около /tools/*.txt

2023-07-11 16:05 UTC, machine-solution requested changes

2023-07-11 16:05 UTC, machine-solution commented on tools/xml_autogen.py
>              f.write(' ' * 8 + f'<pair geom1="geom edge {i}" geom2="geom obstacle {j}"/>\n')
А тут откуда f? Почему не в аргументах?

2023-07-11 16:05 UTC, machine-solution commented on tools/edges.txt
Так а почему здесь до сих пор файл-аргумент?

2023-07-11 16:05 UTC, machine-solution commented on tools/obstacles.txt
И этот тоже?

2023-07-15 06:41 UTC, machine-solution requested changes

2023-07-15 06:41 UTC, machine-solution commented on tools/xml_autogen.py
> +def manipulator_autogen(joints, size, pos):
Давай для таких переменных, как dict, будем это указывать явно в type hint

```
def manipulator_autogen(joints, size: dict, pos: dict)
```

2023-07-15 06:41 UTC, machine-solution commented on tools/xml_autogen.py
> +        output_prefix += f'{current_space + "    "}<geom name=\"geom edge {i} shade\" type=\"cylinder\" size={size["cylinder"]} material=\"green\"/>\n'
Ты ж совсем не то сделал. Куда здесь ввести количество звеньев и их длины? У тебя тут все звенья одинавые, у joint тоже в зависимости от длины будет разный pos. Прежде чем делать пр сгенерируй манипуляторы с разными длинами и запусти проект с ним.

2023-07-15 06:41 UTC, machine-solution commented on tools/xml_autogen.py
> +        output_prefix += f'{current_space + "    "}<geom name=\"geom edge {i} shade\" type=\"cylinder\" size={size["cylinder"]} material=\"green\"/>\n'
И давай в глобальный массив выносить длины звеньев и передавать аргументом.

2023-07-15 06:41 UTC, machine-solution commented on tools/xml_autogen.py
> +def obstacles_autogen(obstacles, obstacles_types, \
А зачем? Договаривались же, что тут особо ничего не придумать.
Давай тогда по файлу типа
```
type="box" size="0.1 0.2 0.3" pos="1.5 0.9 0.0"
type="sphere" size="0.2" pos="0.0 -1.5 0.0"
```

Генерировать секцию
```
        <body name="obstacle 0">
            <geom name="geom obstacle 0" type="box" size="0.1 0.2 0.3" pos="1.5 0.9 0.0" material="blue"/>
        </body>
        <body name="obstacle 1">
            <geom name="geom obstacle 1" type="sphere" size="0.2" pos="0.0 -1.5 0.0" material="blue"/>
        </body>
```

По аргументам совсем неудобно

2023-07-15 06:41 UTC, machine-solution commented
Прошлые замечания ОК, появились новые в стиле "вообще не то сделано"

2023-07-19 16:17 UTC, machine-solution requested changes

2023-07-19 16:17 UTC, machine-solution commented on tools/xml_autogen.py
> +    output += output_prefix + ''.join(output_suffix[-1:-len(output_suffix)-1:-1]) + '\n'
Это же можно вынести в функцию и объединить с кодом выше (про манипулятор без shade). Так и смотрится приятнее и сложнее запутаться.

2023-07-22 08:10 UTC, machine-solution requested changes

2023-07-22 08:10 UTC, machine-solution commented on tools/xml_autogen.py
> +    billet = open(file_path).read()
А почему billet? Почему не data?

2023-07-22 08:10 UTC, machine-solution commented on tools/xml_autogen.py
> +        del billet[-1]
Умно. Но лучше все пустые строки пропускать и делать это в цикле ниже.

2023-07-22 08:10 UTC, machine-solution commented on tools/xml_autogen.py
> +path_to_footer = 'tools/src/const/footer.txt'
С папками что-то плохое творится. src - это папка с исходным кодом, обычно. И почему в ней ещё и папка const лежит - вообще непонятно
Я бы предложил такую структуру:
tools/
|- args/
|- const/
|- xml_autogen.py

2023-07-25 15:50 UTC, machine-solution approved these changes

2023-07-25 15:51 UTC, merged