Refinement-of-autogeneration
machine-solution/motion_planning_for_manipulators pull request #26
Opened 2023-07-31 13:14 UTC by ThirdAmethystEye

2023-08-01 17:18 UTC, machine-solution requested changes

2023-08-01 17:18 UTC, machine-solution commented on tools/args/obstacles.txt
А поч оно всё ещё в репозитории и это не детектит .gitignore. Обсуждали же, что плохо входные данные в репозиторий пушить.

2023-08-01 17:18 UTC, machine-solution commented on tools/xml_autogen.py
> +    global obstacles
Эх, питон пошёл. Давай возвращать количество препятствий в этой функции, а не извращаться

2023-08-01 17:18 UTC, machine-solution commented on tools/xml_autogen.py
> -with open(f'tools/{joints}-dof_{obstacles}-obs_manipulator.xml', "w+") as f:
А чего отказались от названий с количеством препятствий?

2023-08-02 08:05 UTC, ThirdAmethystEye commented on tools/args/obstacles.txt
Понял - принял.

2023-08-05 05:59 UTC, machine-solution approved these changes

2023-08-05 05:59 UTC, merged